### ISSUE TITLE
Integrate with existing worker code?

### ISSUE THREAD

**Issue by ZebraFlesh** [worker-tools/html#1]
How can I integrate this to an existing worker? That is, I'm already able to `fetch` and return a complete HTML document. But I'd like to use `HTMLRewriter` to append some HTML to the document. I can't quite figure it out from the getclaps example -- everything seems to be based around using the `HTMLResponse` function.

**Comment by qwtel** [comment]
> everything seems to be based around using the HTMLResponse function.

Yes that is correct. This library isn't really intended to work with `HTMLRewriter`. As a workaround you could use something like 

```js
await new HTMLResponse(html`...`).text()
```

**Comment by ZebraFlesh** [comment]
Thanks, that works!
