### ISSUE TITLE
Empty string instead of space for falsy elements

### ISSUE THREAD

**Issue by guregu** [worker-tools/html#4]
Hello, thanks for this library! I'm enjoying using it to make a little worker.

I noticed that falsy values become a space instead of an empty string.
This can produce unexpected results when using variables in HTML attributes, for example:
```typescript
let foo: string | null = request.searchParams.get("foo");
return html`<input type="text" value="${foo}" placeholder="hello world">`;
```

This gets rendered as:
```html
<input type="text" value=" " placeholder="hello world">
```
which hides the placeholder and makes 1-1 correlation with `<form method=GET>` difficult.

Desired result:
```html
<input type="text" value="" placeholder="hello world">
```

I was wondering if I am doing something wrong. It seems like there isn't a way to embed an empty string at the moment. 

Apologizes if I missed something!

**Comment by qwtel** [comment]
Ah yes, the space was a fix for odd behavior of streams in older versions of cloudflare workers. I'll investigate if this is still necessary.

**Comment by qwtel** [comment]
There appears to be no issue with the latest version of cloudflare workers, so I'll fix this behavior now. Note that this only applies to the latest preview version v2.0.0-pre.12.

**Comment by guregu** [comment]
Thanks a bunch! I was [able to remove some hacks in my project](https://github.com/guregu/worker-prolog/commit/b30ad4c617649e89e505149541fa69379dc343cd#diff-f4d9dff5b7cf359f6ece2e67222e84e4f22707c9c83982648906873339097314) and it works perfectly now. Much appreciated!
